### ISSUE TITLE
Hosted Metrics vs Grafana Cloud

### ISSUE THREAD

**Issue by tmm1** [grafana/grafanacloud-hosted-metrics-graphite-sender-example#8]
I'm a bit confused about the difference between the two. I thought Grafana Cloud was powered by Cortex? Can I still use the scripts in this repo to feed data into Grafana Cloud?

**Comment by Dieterbe** [comment]
Hi, your confusion is very understandable.
GrafanaCloud Hosted Metrics offers both Graphite (powered by metrictank) and Prometheus (powered by cortex)
This repository predates the Prometheus product. I have renamed this repo and clarified it in the readme.

**Comment by tmm1** [comment]
Thanks for that, it really helps.

Is there any similar solution for grafana hosted Prometheus that would allow me to push metrics via http?

**Comment by Dieterbe** [comment]
that's a question for @tomwilkie

**Comment by tomwilkie** [comment]
> Is there any similar solution for grafana hosted Prometheus that would allow me to push metrics via http?

Our hosted Prometheus service has a HTTP interface for pushing metrics.  They are not particularly well documented[1], but accepted Prometheus remote write formatted requests (ie protobuf encoded and snappy compressed).

[1] https://cortexmetrics.io/docs/apis/#remote-api

**Comment by tmm1** [comment]
Okay great, I'll see if I can get that working with github.com/m3dbx/prometheus_remote_client_golang

Would it be preferable for me to batch metrics together (for example how pushgateway does) before submitting to the remote_write endpoint, or does the cortex backend not care?

**Comment by tomwilkie** [comment]
> Would it be preferable for me to batch metrics together (for example how pushgateway does) before submitting to the remote_write endpoint, or does the cortex backend not care?

Not mandatory, but you'll have much better performance if you do.  Prometheus sends batches of ~100 by default IIRC.

**Comment by tmm1** [comment]
Wonderful, thanks. I was able to use the prometheus_remote_client_golang library to push metrics into grafana hosted cortex!

Does regular prometheus also have a remote_write endpoint? I was trying that earlier to test first, but my local prometheus only returns 404 on `/api/prom/push`.

**Comment by tomwilkie** [comment]
I'm afraid not - regular Prometheus is pull-only.

**Comment by tmm1** [comment]
My use-case involves IoT hardware devices in customer's homes that report metrics so we can give customers visibility into their device. Unfortunately the devices are CPU and RAM constrained, so an API which depends on snappy and protobuf is quite challenging to implement natively on the device.

I'm switching to the graphite hosted metrics backend, and making simple json http requests in the format defined in this repository is working very well. In the future, it would be nice if the prometheus backend was also able to inject metrics via the same format so it was easy for grafana cloud users like me to send our metrics to one or the other with no code changes.
